// bus 的純邏輯公開出口（與 `@/features/route/domain` 同一規則：不得 import react-native／expo）。
export {
  CURRENT_STOP_RADIUS_M,
  buildStopRows,
  equalStopName,
  fallbackStopRows,
  normalizeStopName,
  parseStatusLabel,
  resolveCurrentStopSeq,
  resolveEtaLabel,
  resolveLegDirection,
  resolveLegRide,
  resolveLegStops,
  sliceLegStops,
  type BusLegStopRow,
  type EtaLabel,
  type EtaLabelKind,
  type EtaTone,
  type LegRide,
  type LegRideRef,
  type StopRowKind,
  type StopRowState,
} from './busLegStops';
export {
  BUS_TWEEN_DURATION_MS,
  buildBusTweens,
  busFrame,
  easeOutCubic,
  type AnimatedBus,
  type BusTween,
  type DrawnPosition,
} from './busTween';
export {
  BUS_STATUS,
  type BusArrivalData,
  type BusArrivalItem,
  type BusDirection,
  type BusSearchResult,
  type BusStopSearchResult,
  type LiveBus,
  type LiveBusPositionsData,
  type RouteDetailDirection,
  type RouteDetailStop,
  type StopArrival,
  type StopArrivalsData,
  type TrackableBusDirection,
} from '../types/transit';
export { BUS_CITY_NAMES, busCityLabel, groupByCity, type BusCityGroup } from './busCities';
export { resolveStopBadge, type BusStopBadge, type BusStopBadgeKind, type BusStopBadgeTone } from './busStopBadge';
export {
  belongsToSelection,
  buildDirectionOptions,
  directionTitle,
  isBusDirection,
  isTrackableDirection,
  matchesSelection,
  pickNextArrival,
  resolveDirectionOption,
  routePathOfOption,
  selectionOf,
  stopsOfOption,
  stripLiveEta,
  type DirectionOption,
  type DirectionPreference,
  type DirectionTitle,
  type NextArrival,
  type RideSelection,
} from './busDirections';
export { firstParam, parseDirectionParam, parseFiniteParam, parseRouteListParam } from './screenParams';
export {
  EMPTY_LIVE_BUSES,
  isAccessibleBus,
  liveBusCollection,
  selectDisplayBuses,
  type LiveBusProps,
} from './liveBusGeoJson';
export { resolveLiveEta, resolveWaitText, type LegText, type LiveEta, type LiveEtaTone } from './legBadges';
export {
  BUS_AT_STOP_RADIUS_M,
  isAccessibleArrival,
  matchStopInRoute,
  nextBusToStop,
  pickFeaturedArrival,
  placeBuses,
  routesWithoutArrivals,
  sortArrivals,
  stopsBounds,
  type ApproachingBus,
  type PlacedBus,
  type StopMatch,
} from './stopBoard';
